DjangoStudyBuddyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('account/', include('account.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('profile/<int:pk>', views.UserProfileView.as_view(), name='profile-detail'),
    path('login/', views.UserLoginView.as_view(), name='login'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    # room URL
    path('room/<int:pk>/<slug:slug>', views.RoomDetailView.as_view(), name='room-detail'),
    path('', views.HomeView.as_view(), name='home'),
    path('createroom', views.CreateRoomView.as_view(), name='create-room'),
    path('search/', views.SearchRoomView.as_view(), name='search-room'),
    path('deleteroom/<int:pk>', views.DeleteRoomView.as_view(), name='delete-room'),

    # topic URL
    path('topic/<int:pk>', views.TopicDetailView.as_view(), name='topic-detail'),
    path('topics', views.TopicListView.as_view(), name='topic'),
    path('topics/create', views.CreateTopicView.as_view(), name='create-topic'),

    # Message URL
    path('deletemesssge/<int:pk>', views.DeleteMessageView.as_view(), name='delete-message'),
]

core/models.py
from account.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Topic(models.Model):
    name = models.CharField(max_length=155)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, default='userNotFound', on_delete=models.SET_DEFAULT,  related_name='rooms')
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='rooms')
    name = models.CharField(max_length=155)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField()
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ('-updated', '-created')

    def __str__(self):
        return f'{self.name} - {self.host}'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.name)
        super(Room, self).save()

    def get_absolute_url(self):
        return reverse('core:room-detail', kwargs={'pk': self.pk, 'slug': self.slug})


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='message')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='message')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ('-updated', '-created')

    def __str__(self):
        return f'{self.user}|{self.room}--{self.text[:25]}'

core/forms.py
from django import forms
from .models import Message
from django.forms import ValidationError, TextInput

class MessageFrom(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('text',)
        widgets = {
                'text': TextInput(attrs={'class':'room__message', 'placeholder': 'Write Your Message'})
        }

core/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DeleteView, ListView,
                                  TemplateView, View)

from .forms import MessageFrom
# from .mixins import AddTopicMixins
from .models import Message, Room, Topic
from django.contrib.auth.mixins import LoginRequiredMixin


class HomeView(TemplateView):
    template_name = 'core/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rooms'] = Room.objects.filter(status=True)
        context['topics'] = Topic.objects.all()
        context['messages'] = Message.objects.filter(status=True)

        # get number_of_rooms
        number_of_rooms = 0
        for i in context['topics']:
            room = i.rooms.count()
            number_of_rooms = number_of_rooms + room
        context['count_all_room'] = number_of_rooms
        return context


class CreateRoomView(CreateView):
    model = Room
    fields = ['topic', 'name', 'description']
    template_name = 'core/create_room.html'
    success_url = reverse_lazy('core:home')

    def form_valid(self, form):
        form.instance.host = self.request.user
        return super().form_valid(form)


class DeleteMessageView(DeleteView):
    model = Message
    template_name = 'core/confirm_delete.html'

    def get_success_url(self):
        room = Room.objects.get(id=self.object.room.id)
        test = Message.objects.filter(user=self.request.user, room=room)
        print(test.count())
        if test.count() == 1:
            room.participants.remove(self.request.user)
        return reverse('core:home')


class TopicDetailView(View):
    def setup(self, request, *args, **kwargs):
        self.topic = get_object_or_404(Topic, id=kwargs['pk'])
        self.rooms = self.topic.rooms.filter(status=True)
        self.topics = Topic.objects.all()
        self.message = Message.objects.filter(status=True)
        return super().setup(request, *args, **kwargs)

    def get(self, request, *arge, **kwarge):
        rooms = self.rooms
        topics = self.topics
        message = self.message

        context = {
            'rooms': rooms,
            'topics': topics,
            'messages': message,

        }
        return render(request, 'core/home.html', context)


class TopicListView(ListView):
    model = Topic
    template_name = 'core/topics.html'
    context_object_name = 'topics'

    def get_queryset(self, *args, **kwargs):
        topics = super().get_queryset(*args, **kwargs)

        q = self.request.GET.get('q')
        if q:
            return Topic.objects.filter(name__icontains=q)
        return topics


class SearchRoomView(ListView):
    model = Room
    template_name = 'core/home.html'
    context_object_name = 'rooms'

    def get_queryset(self):
        rooms = super().get_queryset()

        q = self.request.GET.get('q')
        if q:
            return Room.objects.filter(
                Q(topic__name__icontains=q) |
                Q(name__icontains=q) |
                Q(description__icontains=q)
            ).filter(status=True)
        return rooms

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['topics'] = Topic.objects.all()
        context['messages'] = Message.objects.filter(status=True)
        return context


class RoomDetailView(View):
    message_form_class = MessageFrom

    def setup(self, request, *args, **kwargs):
        self.room = get_object_or_404(Room, id=kwargs['pk'], slug=kwargs['slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *arge, **kwarge):
        room = self.room
        messages = room.message.all()
        context = {
            'room': room,
            'messages': messages,
            'form': self.message_form_class
        }
        return render(request, 'core/room.html', context)

    def post(self, request, *args, **kwargs):
        form = self.message_form_class(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.user = request.user
            message.room = self.room
            self.room.participants.add(request.user)  # for add new user to participants
            message.save()
            return redirect('core:room-detail', self.room.id, self.room.slug)


class DeleteRoomView(DeleteView):
    model = Room
    success_url = reverse_lazy('core:home')
    template_name = 'core/confirm_delete.html'

# AddTopicMixins
class CreateTopicView(LoginRequiredMixin, CreateView):
    model = Topic
    fields = ['name']
    template_name = 'core/create_topic.html'
    success_url = reverse_lazy('core:home')

core/templates/core/confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

core/templates/core/create_room.html
{% extends 'base.html' %}
{% load static %}

{% block tiitle %}<title>Create Room</title>{% endblock %}

{% block content %}
    <main class="create-room layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Create Study Room</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="#" method="post">
                        {% csrf_token %}
                        <div class="form__group">
                            {{ form }}
                            <div class="form__action">
                                <a class="btn btn--dark" href="index.html">Cancel</a>
                                <button class="btn btn--main" type="submit">Create Room</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock %}  

core/templates/core/home.html
{% extends 'base.html' %}
{% load static %}

{% block tiitle %}<title>home</title>{% endblock %}

{% block content %}
    <main class="layout layout--3">
        <div class="container">
            <!-- Topics Start -->
            <div class="topics">
                <div class="topics__header">
                    <h2>Browse Topics</h2>
                </div>
                <ul class="topics__list">
                    <li>
                        <a href="/" class="active">All <span>{{ topics.count }}</span></a>
                    </li>
                    {% for topic in topics %}
                        <li>
                            <a href="{% url 'core:topic-detail' topic.id %}">{{ topic.name }}<span>{{ topic.rooms.count }}</span></a>
                        </li>
                    {% endfor %}
                </ul>
                <a class="btn btn--link" href="{% url 'core:topic' %}">
                    More
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>chevron-down</title>
                        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
                    </svg>
                </a>
            </div>
            <!-- Topics End -->

            <!-- Room List Start -->
            <div class="roomList">
                <div class="mobile-menu">
                    <form class="header__search">
                        <label>
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>search</title>
                                <path
                                        d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                                ></path>
                            </svg>
                            <input placeholder="Search for posts"/>
                        </label>
                    </form>
                    <div class="mobile-menuItems">
                        <a class="btn btn--main btn--pill" href="#">Browse Topics</a>
                        <a class="btn btn--main btn--pill" href="#">Recent Activities</a>
                    </div>
                </div>
                <div class="roomList__header">
                    <div>
                        <h2>Study Room</h2>
                        <p>{{ count_all_room }} Rooms available</p>
                    </div>
                    <a class="btn btn--main" href="{% url 'core:create-room' %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                             viewBox="0 0 32 32">
                            <title>add</title>
                            <path
                                    d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                            ></path>
                        </svg>
                        Create Room
                    </a>
                </div>
                {% for room in rooms %}
                    <div class="roomListRoom">
                        <div class="roomListRoom__header">
                            <a href="{% url 'account:profile-detail' room.host.id %}" class="roomListRoom__author">
                                <div class="avatar avatar--small">
                                    
                                    {% if room.host.avatar %}
                                    <img src="{{ room.host.avatar.url }}"/>
                                    {% else %}
                                    <img src="{% static 'assets/images/sutdent-prof.png' %}" />
                                    {% endif %}
                                        
                                    
                                </div>
                                <span>@{{ room.host }}</span>
                            </a>
                            <div class="roomListRoom__actions">
                                <span>{{ room.created|timesince }}</span>
                            </div>
                        </div>
                        <div class="roomListRoom__content">
                            <a href="{{ room.get_absolute_url }}"> {{ room.name }} </a>
                            <p>
                                {{ room.description }}
                            </p>
                        </div>
                        <div class="roomListRoom__meta">
                            <a href="room.html" class="roomListRoom__joined">
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                     viewBox="0 0 32 32">
                                    <title>user-group</title>
                                    <path
                                            d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
                                    ></path>
                                    <path
                                            d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
                                    ></path>
                                    <path
                                            d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
                                    ></path>
                                    <path
                                            d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
                                    ></path>
                                </svg>
                                {{ room.participants.count }} Joined
                            </a>
                            <p class="roomListRoom__topic">{{ room.topic }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <!-- Room List End -->

            <!-- Activities Start -->
            <div class="activities">
                <div class="activities__header">
                    <h2>Recent Activities</h2>
                </div>
                {% for message in messages %}
                    <div class="activities__box">
                        <div class="activities__boxHeader roomListRoom__header">
                            <a href="{% url 'account:profile-detail' message.user.id %}" class="roomListRoom__author">
                                <div class="avatar avatar--small">
                                    {% if message.user.avatar %}
                                    <img src="{{  message.user.avatar.url }}"/>
                                    {% else %}
                                    <img src="{% static 'assets/images/sutdent-prof.png' %}" />
                                    {% endif %}                                </div>
                                <p>
                                    @{{ message.user.username }}
                                    <span>5 days ago</span>
                                </p>
                            </a>
                             {% if request.user == message.user %}
                            <div class="roomListRoom__actions">

                                <a href="{% url 'core:delete-message' message.id %}">
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                         viewBox="0 0 32 32">
                                        <title>remove</title>
                                        <path
                                                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                                        ></path>
                                    </svg>
                                </a>
                            </div>
                            {% endif %}
                        </div>
                        <div class="activities__boxContent">
                            <p>replied to post “<a href="room.html">{{ message.room.name }}</a>”</p>
                            <div class="activities__boxRoomContent">
                                {{ message.text }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <!-- Activities End -->
        </div>
    </main>
{% endblock %}

core/templates/core/message_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

core/templates/core/room.html
{% extends 'base.html' %}
{% load static %}

{% block tiitle %}<title>home</title>{% endblock %}

{% block content %}
<main class="profile-page layout layout--2">
    <div class="container">
        <!-- Room Start -->
        <div class="room">
            <div class="room__top">
                <div class="room__topLeft">
                    <a href="index.html">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Study Room</h3>
                </div>

                <div class="room__topRight">
                    <a href="#">
                        <svg enable-background="new 0 0 24 24" height="32" viewBox="0 0 24 24" width="32"
                            xmlns="http://www.w3.org/2000/svg">
                            <title>edit</title>
                            <g>
                                <path
                                    d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                            </g>
                            <g>
                                <g>
                                    <path
                                        d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z" />
                                </g>
                                <g>
                                    <path
                                        d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z" />
                                </g>
                            </g>
                        </svg>
                    </a>
                    <a href="{% url 'core:delete-room' room.id %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>remove</title>
                            <path
                                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                            </path>
                        </svg>
                    </a>
                </div>

                <!-- <button class="action-button" data-id="120" data-delete-url="https://randomuser.me/api/3324923"
                    data-edit-url="profile.html">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>ellipsis-horizontal</title>
                      <path
                        d="M16 7.843c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 1.98c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
                      </path>
                      <path
                        d="M16 19.908c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 14.046c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
                      </path>
                      <path
                        d="M16 31.974c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 26.111c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
                      </path>
                    </svg>
                  </button> -->
            </div>
            <div class="room__box scroll">
                <div class="room__header scroll">
                    <div class="room__info">
                        <h3>{{ room.name }}</h3>
                        <span>{{ room.created|timesince }} ago</span>
                    </div>
                    <div class="room__hosted">
                        <p>Hosted By</p>
                        <a href="#" class="room__author">
                            <div class="avatar avatar--small">
                                {% if room.host.avatar %}
                                <img src="{{ room.host.avatar.url }}" />
                                {% else %}
                                <img src="{% static 'assets/images/sutdent-prof.png' %}" />
                                {% endif %}
                            </div>
                            <span>@{{ room.host }}</span>
                        </a>
                    </div>
                    <div class="room__details">
                        <p>
                            {{ room.description }}
                        </p>
                    </div>
                    <span class="room__topics">{{ room.topic }}</span>
                </div>
                <div class="room__conversation">
                    <div class="threads scroll">
                        {% for message in messages %}
                        <div class="thread">
                            <div class="thread__top">
                                <div class="thread__author">
                                    <a href="#" class="thread__authorInfo">
                                        <div class="avatar avatar--small">
                                            {% if message.user.avatar %}
                                            <img src="{{ message.user.avatar.url }}" />
                                            {% else %}
                                            <img src="{% static 'assets/images/sutdent-prof.png' %}" />
                                            {% endif %}
                                        </div>
                                        <span>@{{ message.user.username }}</span>
                                    </a>
                                    <span class="thread__date">{{ message.created|timesince }} ago</span>
                                </div>
                                <div class="thread__delete">
                                    <a href="{% url 'core:delete-message' message.id %}">
                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                            viewBox="0 0 32 32">
                                            <title>remove</title>
                                            <path
                                                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                                            </path>
                                        </svg>
                                    </a>
                                </div>
                            </div>
                            <div class="thread__details">
                                <p>
                                    {{ message.text }}
                                </p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            
            {% if request.user.is_authenticated %}
                <div class="room__message">
                    <form method="post" action="#">
                        {% csrf_token %}
                        {{ form.text }}
                        <!-- <input type="submit"> -->
                    </form>
                </div>
            {% else %}
            <div class="room__message">
                <a class="btn btn--main" href="{% url 'account:login' %}">please login for send message</a>
            </div>
            
            {% endif %}
                
            
        </div>
        <!-- Room End -->

        <!--   Start -->
        <div class="participants">
            <h3 class="participants__top">Participants <span>(5.3k Joined)</span></h3>
            <div class="participants__list scroll">
                {% for user in room.participants.all %}
                <a href="profile.html" class="participant">
                    <div class="avatar avatar--medium">
                        {% if user.avatar %}
                        <img src="{{ user.avatar.url }}" />
                        {% else %}
                        <img src="{% static 'assets/images/sutdent-prof.png' %}" />
                        {% endif %}
                    </div>
                    <p>
                        {{ user.first_name }} {{ user.last_name }}
                        <span>@{{ user.username }}</span>
                    </p>
                </a>
                {% endfor %}
            </div>
        </div>
        <!--  End -->
    </div>
</main>
{% endblock %}

core/templates/core/topics.html
{% extends 'base.html' %}
{% load static %}

{% block tiitle %}<title>Topics</title>{% endblock %}
{% block content %}
<main class="create-room layout" >
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="index.html">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Browse Topics</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <form class="header__search" >
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input placeholder="Search for posts" name="q">
          </label>
        </form>

        <ul class="topics__list">
          <li>
            <a href="/" class="active">All <span>553</span></a>
          </li>
          {% for topic in topics %}
          <li>
            <a href="{% url 'core:topic-detail' topic.id %}">{{ topic.name }} <span>{{ topic.rooms.count }}</span></a>
          </li>
          {% endfor %}

        </ul>
      </div>
    </div>
  </div>
</main>
{% endblock %}